### ISSUE TITLE
Deadlock occurs if `poll` and `reset!` are called at the same time

### ISSUE THREAD

**Issue by abicky** [joker1007/crono_trigger#11]
We will receive an error message lke "Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction" if we execute the following code:

```ruby
require 'crono_trigger'
require 'serverengine'

ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  database: "test",
  pool: 20,
)

class Notification < ActiveRecord::Base
  include CronoTrigger::Schedulable
  self.ignored_columns = %w[last_error_name last_error_reason last_error_time]

  def execute
    Thread.new { reset! }
  end
end

Notification.transaction do
  now = Time.now
  Notification.delete_all
  100.times do |i|
    Notification.create!(next_execute_at: now, started_at: now)
  end
end


CronoTrigger.config.model_names = ["Notification"]

Array.new(10) do
  Thread.new do
    Class.new { include CronoTrigger::Worker }.new.tap do |w|
      logger = Logger.new($stdout, level: Logger::WARN)
      w.instance_variable_set(:@logger, logger)
      ActiveRecord::Base.logger = logger
    end.run
  end
end.each(&:join)
```

Here is an output:

```
E, [2018-12-05T15:39:43.738812 #29132] ERROR -- : Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UPDATE `notifications` SET `next_execute_at` = NULL, `execute_lock` = 0, `locked_by` = NULL, `last_executed_at` = '2018-12-05 06:39:43', `retry_count` = 0 WHERE `notifications`.`id` = 15153 (ActiveRecord::Deadlocked)
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/mysql/database_statements.rb:45:in `exec_delete'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:157:in `update'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `update'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/persistence.rb:197:in `_update_record'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/persistence.rb:476:in `update_columns'
/Users/arabiki/ghq/src/github.com/joker1007/crono_trigger/lib/crono_trigger/schedulable.rb:195:in `reset!'
/Users/arabiki/ghq/src/github.com/joker1007/crono_trigger/lib/crono_trigger/schedulable.rb:122:in `block (2 levels) in do_execute'
/Users/arabiki/ghq/src/github.com/joker1007/crono_trigger/lib/crono_trigger/schedulable.rb:110:in `catch'
/Users/arabiki/ghq/src/github.com/joker1007/crono_trigger/lib/crono_trigger/schedulable.rb:110:in `block in do_execute'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/arabiki/ghq/src/github.com/joker1007/crono_trigger/lib/crono_trigger/schedulable.rb:109:in `do_execute'
/Users/arabiki/ghq/src/github.com/joker1007/crono_trigger/lib/crono_trigger/polling_thread.rb:69:in `block (3 levels) in poll'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/Users/arabiki/ghq/src/github.com/joker1007/crono_trigger/lib/crono_trigger/polling_thread.rb:66:in `block (2 levels) in poll'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/arabiki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

Here is a partial result of `show engine innodb status`:

```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2018-12-05 15:39:43 0x700001397000
*** (1) TRANSACTION:
TRANSACTION 49134, ACTIVE 0 sec updating or deleting
mysql tables in use 1, locked 1
LOCK WAIT 4 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 1
MySQL thread id 8798, OS thread handle 123145320345600, query id 90181 localhost root updating
UPDATE `notifications` SET `next_execute_at` = NULL, `execute_lock` = 0, `locked_by` = NULL, `last_executed_at` = '2018-12-05 06:39:43', `retry_count` = 0 WHERE `notifications`.`id` = 15154
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 206 page no 4 n bits 248 index crono_trigger_index_on_notifications of table `test`.`notifications` trx id 49134 lock_mode X locks gap before rec insert intention waiting
Record lock, heap no 102 PHYSICAL RECORD: n_fields 5; compact format; info bits 0
 0: len 5; hex 99a18a69e6; asc    i ;;
 1: len 8; hex 800000005c0772af; asc     \ r ;;
 2: len 5; hex 99a18a69e6; asc    i ;;
 3: SQL NULL;
 4: len 4; hex 80003b1d; asc   ; ;;

*** (2) TRANSACTION:
TRANSACTION 49092, ACTIVE 0 sec fetching rows
mysql tables in use 1, locked 1
7 lock struct(s), heap size 1136, 28 row lock(s)
MySQL thread id 8793, OS thread handle 123145322852352, query id 90129 localhost root Sending data
SELECT  `notifications`.`id`, `notifications`.`name`, `notifications`.`cron`, `notifications`.`next_execute_at`, `notifications`.`last_executed_at`, `notifications`.`timezone`, `notifications`.`execute_lock`, `notifications`.`locked_by`, `notifications`.`started_at`, `notifications`.`finished_at`, `notifications`.`retry_count`, `notifications`.`created_at`, `notifications`.`updated_at` FROM `notifications` WHERE `notifications`.`next_execute_at` <= '2018-12-05 06:39:43' AND `notifications`.`execute_lock` <= 1543991383 AND `notifications`.`started_at` <= '2018-12-05 06:39:43' AND (`notifications`.`finished_at` > '2018-12-05 06:39:43' OR `notifications`.`finished_at` IS NULL) ORDER BY `notifications`.`next_execute_at` ASC LIMIT 75 FOR UPDATE
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 206 page no 4 n bits 248 index crono_trigger_index_on_notifications of table `test`.`notifications` trx id 49092 lock_mode X locks gap before rec
Record lock, heap no 102 PHYSICAL RECORD: n_fields 5; compact format; info bits 0
 0: len 5; hex 99a18a69e6; asc    i ;;
 1: len 8; hex 800000005c0772af; asc     \ r ;;
 2: len 5; hex 99a18a69e6; asc    i ;;
 3: SQL NULL;
 4: len 4; hex 80003b1d; asc   ; ;;

Record lock, heap no 109 PHYSICAL RECORD: n_fields 5; compact format; info bits 0
 0: len 5; hex 99a18a69e6; asc    i ;;
 1: len 8; hex 800000005c0772af; asc     \ r ;;
 2: len 5; hex 99a18a69e6; asc    i ;;
 3: SQL NULL;
 4: len 4; hex 80003b24; asc   ;$;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 206 page no 4 n bits 248 index crono_trigger_index_on_notifications of table `test`.`notifications` trx id 49092 lock_mode X waiting
Record lock, heap no 123 PHYSICAL RECORD: n_fields 5; compact format; info bits 32
 0: len 5; hex 99a18a69e6; asc    i ;;
 1: len 8; hex 800000005c0772af; asc     \ r ;;
 2: len 5; hex 99a18a69e6; asc    i ;;
 3: SQL NULL;
 4: len 4; hex 80003b32; asc   ;2;;

*** WE ROLL BACK TRANSACTION (1)
```

**Comment by abicky** [comment]
This issue was resolved by https://github.com/joker1007/crono_trigger/pull/12
